# Generated by Django 6.0 on 2026-01-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, choices=[('cit', 'CIT'), ('coa', 'COA'), ('coed', 'COED'), ('chm', 'CHM'), ('cba', 'CBA')], max_length=10, null=True),
        ),
    ]
