# Generated by Django 6.0 on 2026-01-13 08:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OJTListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., OJT Intern - IT Department', max_length=200)),
                ('ojt_type', models.CharField(choices=[('required', 'Required (400-500 hours)'), ('elective', 'Elective/Optional'), ('summer', 'Summer OJT')], default='required', max_length=20)),
                ('required_hours', models.IntegerField(default=500)),
                ('duration_weeks', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(26)])),
                ('work_setup', models.CharField(choices=[('onsite', 'On-site (Face to Face)'), ('hybrid', 'Hybrid (Some WFH)'), ('wfh', 'Work From Home')], default='onsite', max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='What will the OJT intern do?')),
                ('responsibilities', models.TextField(help_text='Specific tasks and responsibilities')),
                ('learning_outcomes', models.TextField(help_text='What skills will the intern gain?')),
                ('course_requirement', models.CharField(choices=[('cit', 'Information Technology (CIT)'), ('coa', 'Accountancy (COA)'), ('coed', 'Education (COED)'), ('chm', 'Hospitality Management (CBA)'), ('cba', 'Business Administration (CBA)'), ('all', 'All Courses')], default='all', help_text='Which course is this OJT for?', max_length=20)),
                ('year_level_requirement', models.IntegerField(choices=[(3, '3rd Year'), (4, '4th Year'), (0, 'Any Year Level')], default=4)),
                ('skills_required', models.TextField(blank=True, help_text='e.g., Basic programming, MS Office, Communication skills')),
                ('slots_available', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('has_allowance', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('application_deadline', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open for Applications'), ('filled', 'Positions Filled'), ('closed', 'Closed'), ('ongoing', 'OJT Ongoing')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/%d/')),
                ('transcript', models.FileField(blank=True, null=True, upload_to='transcripts/%Y/%m/%d/')),
                ('endorsement_letter', models.FileField(blank=True, null=True, upload_to='endorsements/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('for_interview', 'For Interview'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.DateTimeField(blank=True, null=True)),
                ('interview_notes', models.TextField(blank=True)),
                ('final_feedback', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.ojtlisting')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('student', 'listing')},
            },
        ),
    ]
